# 值与：之间一定要有一个空格，否则无效
# Server settings
server:
    port: 8020
    address: localhost

## DATASOURCE
jdbc:
    driverClass: com.mysql.jdbc.Driver
    url: jdbc:mysql://58.210.177.89:33639/pas_dev?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: pas_user
    password: kashuo_pasdev_password

# SPRING PROFILES
spring:
    # HTTP ENCODING
    http:
        encoding.charset: UTF-8
        encoding.enable: true
        encoding.force: true

    thymeleaf:
        cache: false

## Mybatis
#mybatis:
#    typeAliasesPackage: org.hemoo.**.domain
#    mapperLocations: classpath:/org/hemoo/**/mapper/*.xml
#    configLocation: classpath:/mybatis-config.xml
